config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

	root "welcome#index"
	devise_for :users
	resources :users, only: [:new, :create]
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :clients
	resources :receipts
	resources :routes
	resources :cajeros
	resources :analiticas
	
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  address    :string
#  phone      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Client < ApplicationRecord
	has_many :receipts
	has_one :user
	belongs_to :route
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	
	before_action :authenticate_user!
	
	def index
		@clients = Client.take(60)
	end

	def show
		@client = Client.find(params[:id])
	end
	
	def new
		@client = Client.new
	end

	def create
		@client = Client.create(client_params)
		if @client.save
			redirect_to clients_path, notice: "Client successfully published"
		else
			render :new
		end
	end

	def edit
		@client = Client.find(params[:id])
	end

	def update
		@client = Client.find(params[:id])
		if @client.update(client_params)
			redirect_to clients_path, notice: "Current Client"
		else
			render :edit
		end
	end

	def destroy
		client = Client.find(params[:id])
		client.destroy

		redirect_to clients_path, notice: "Client delete successfully"
	end

	private
	def client_params
		params.require(:client).permit(:name, :address, :email, :phone, :route_id )
	end

end

app/helpers/clients_helper.rb
module ClientsHelper
	def form_title_client
		@client.new_record? ? "Crear Cliente" : "Modificar Cliente"
	end
	def header_style
		if @client.image.exists?
			%{ style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('#{@client.image.url}'); background-size: cover; background-position: center;" }.html_safe
		else
			""
		end
	end
end

app/views/clients/_form.html.erb
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h2><%= form_title_client %></h2>

		<% if @client.errors.any? %>
		<div class="alert alert-danger">
			<ul>
				<% @client.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>

		<%= form_for @client do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control input-lg" , placeholder: "Ingresa el nombre del cliente" %>
		</div>

		<div class="form-group">
			<%= f.label "Ruta" %>
			<%= f.number_field :route_id, class: "form-control input-lg" , placeholder: "Ingresa la ruta" %>
		</div>
		<div class="form-group">
			<%= f.label :address %>
			<%= f.text_field :address, class: "form-control input-lg" , placeholder: "Ingresa la direccion" %>
		</div>

		<div class="form-group">
			<%= f.label :phone %>
			<%= f.text_field :phone, class: "form-control input-lg" , placeholder: "Ingresa el telefono del cliete" %>
		</div>      
		<div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email, class: "form-control input-lg" , placeholder: "Ingresa el email del cliente" %>
		</div>



		<div class="form-group">
			<%= f.submit form_title_client, class: "btn btn-primary btn-lg" %>
		</div>

		<% end %>
	</div>

app/views/clients/index.html.erb
<div class="row">

	<div class="col-sm-8"><h1 class="text-primary">Clientes</h1></div>
	<div class="col-sm-4"><%= link_to "Nuevo Cliente", new_client_path, class: "btn btn-primary" %></div>
</div>

<div class="row">
	<div class="col-sm-9">
		<table class="table table-bordered table-hover table-striped">
			<thead>
				<tr>
					<th>Codigo</th>
					<th>Ruta</th>
					<th>Cliente</th>
					<th>Direccion</th>
					<th>Telefono</th>
					<th>E-mail</th>
					<th>Edit</th>
				</tr>
			</thead>
			<tbody>
				<% @clients.each do |client| %>
				<tr>
					<td><%= client.id %></td>
					<td><%= client.route.id %> : <%= client.route.ruta %></td>
					<td><%= link_to client.name, client_path(client) %></td>
					<td><%= client.address %></td>
					<td><%= client.phone %></td>
					<td><%= client.email %></td>
					<td><%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_client_path(client)%></td>

				</tr>
						
				<% end %>
			</tbody>
		</table>
		
		
	</div>
</div>

app/views/clients/show.html.erb
<div class="row">
	<h3 class="text-center"><%= @client.name %></h3>
	<div class="col-sm-offset-2 col-sm-8 ">
		<div class="panel panel-default">
			<div class="panel-body">
				<div>Direccion: <%= @client.address %></div>
				<div>Telfono: <%= @client.phone %></div>
				<div>E-mail: <%= @client.email %></div>
				<div>Ruta: <%= link_to @client.route.ruta, route_path(@client.route) %></div>
				
				<hr>
				<div class="text-right">Comprobantes</div>
				<ul class="list-group">
					<% @client.receipts.each do |receipt| %>
					<li class="list-group-item">
					<%= link_to "Comprobante No. "+receipt.id.to_s, receipt_path(receipt) %> de <%= receipt.created_at.strftime("%B %d de  %Y") %><br>Valor :  
					<%= number_to_currency(receipt.amount, precision: 1) %> </li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>