config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

	root "welcome#index"
	devise_for :users
	resources :users, only: [:new, :create]
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :clients
	resources :receipts
	resources :routes
	resources :cajeros
	resources :analiticas
	
end

app/models/route.rb
# == Schema Information
#
# Table name: routes
#
#  id         :integer          not null, primary key
#  ruta       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Route < ApplicationRecord
	has_many :clients
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
		before_action :authenticate_user!
	
	def index
		@routes = Route.all
	end
	
	def show
		@route = Route.find(params[:id])
	end
	

	def new
		@route = Route.new
	end

	def create
		@route = Route.create(route_params)
		if @route.save
			redirect_to routes_path, notice: "Route successfully published"
		else
			render :new
		end
	end

	def edit
		@route = Route.find(params[:id])
	end

	def update
		@route = Route.find(params[:id])
		if @route.update(route_params)
			redirect_to routes_path, notice: "Current Route"
		else
			render :edit
		end
	end

	def destroy
		route = Route.find(params[:id])
		route.destroy

		redirect_to routes_path, notice: "Route delete successfully"
	end

	private
	def route_params
		params.require(:route).permit(:ruta)
	end
end

app/helpers/routes_helper.rb
module RoutesHelper
	def form_title_route
		@route.new_record? ? "Crear Ruta" : "Modificar Ruta"
	end
	def header_style
		if @route.image.exists?
			%{ style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('#{@route.image.url}'); background-size: cover; background-position: center;" }.html_safe
		else
			""
		end
	end
end

app/views/routes/_form.html.erb
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2><%= form_title_route %></h2>

      <% if @route.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @route.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <%= form_for @route do |f| %>
      <div class="form-group">
       	<%= f.label :ruta %>
        <%= f.text_field :ruta, class: "form-control input-lg" , placeholder: "Ingresa el nombre de la ruta" %>
      </div>



      <div class="form-group">
        <%= f.submit form_title_route, class: "btn btn-primary btn-lg" %>
      </div>

      <% end %>
    </div

app/views/routes/edit.html.erb
<%= render 'form' %>

app/views/routes/index.html.erb
<div class="row">

	<div class="col-sm-8"><h1 class="text-primary">Rutas</h1></div>
	<div class="col-sm-4"><%= link_to "Nueva Ruta", new_route_path, class: "btn btn-primary" %></div>
</div>

<div class="row">
	<div class="col-sm-9">
		<table class="table table-bordered table-hover table-striped">
			<thead>
				<tr>
					<th>Codigo</th>
					<th>Ruta</th>
					<th>Edit</th>

				</tr>
			</thead>
			<tbody>
				<% @routes.each do |route| %>
				<tr>
					<td><%= route.id %></td>
					<td><%= link_to route.ruta, route_path(route) %></td>

					<td><%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe, edit_route_path(route)%></td>

				</tr>
						
				<% end %>
			</tbody>
		</table>
		
		
	</div>
</div>

app/views/routes/new.html.erb
<%= render 'form' %>

app/views/routes/show.html.erb
<div class="row">
	<h2>Ruta: <%= @route.ruta%></h2>
	<div class="col-sm-offset-3 col-sm-6">
		<div class="list-group">
		<% @route.clients.each do |client|%>
			<%= link_to client_path(client), class: "list-group-item"  do %>
				<span><%= client.id %>, <strong><%= client.name %></strong>  Dir: <%= client.address%> </span>
			<% end %>
		<% end %>
		</div>
	</div>
</div>