config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

	root "welcome#index"
	devise_for :users
	resources :users, only: [:new, :create]
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	resources :clients
	resources :receipts
	resources :routes
	resources :cajeros
	resources :analiticas
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Colcan</title>
		<%= csrf_meta_tags %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>

		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-10 col-sm-offset-1">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<%= link_to "Colcan", root_path, class: "navbar-brand" %>
						</div>

						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav">

							</ul>
							<ul class="nav navbar-nav navbar-right">
								<% if user_signed_in? %>
								<li><%= link_to current_user.name   %></li>
								<% if current_user.admin? || current_user.logistica? %>
									<li><%= link_to "Rutas", routes_path %></li>
									<li><%= link_to "Clientes" , clients_path %></li>
									<li><%= link_to "Comprobantes", receipts_path %></li>
								<% end %>

								<% if current_user.admin? || current_user.cajero? %>
									<li><%= link_to "Cajero", cajeros_path %></li>
								<% end %>
								<% if current_user.admin? || current_user.preanalitica? %>
									<li><%= link_to "PreAnalitica", analiticas_path %></li>
								<% end %>
								<li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
								<% else %>
								<li><%= link_to "Ingresar", new_user_session_path%></li>
								<li><%= link_to "Registrarse", new_user_registration_path %></li>
								<% end %>
							</ul>
							<!--							<form class="navbar-form navbar-right" role="search">
<div class="form-group">
<input type="text" class="form-control" placeholder="Search">
</div>
</form>-->
						</div><!-- /.navbar-collapse -->
					</div>
				</div>
			</div><!-- /.container -->
		</nav>

		<% if flash[:notice] %>

		<div class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<%= flash[:notice] %>
		</div>	

		<% end %>


		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>